import "@/sass/globals.scss";
import styles from "@/sass/RootLayout.module.scss";
import NotificationsProvider from "@/contexts/NotificationsProvider";
import Header from "@/templates/Header";
import Sidebar from "@/templates/Sidebar";
import Notifications from "@/templates/Notifications";
import { authenticateUser } from "@/utils/auth";
export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};
const RootLayout = async ({ children }) => {
  const { status } = await authenticateUser();
  return (
    <html lang="en">
      <body>
        <NotificationsProvider>
          <Header status={status} />
          <div className={styles.container}>
              <Sidebar status={status} />
              {children}
          </div>
          <Notifications />
        </NotificationsProvider>
      </body>
    </html>
  );
};
export default RootLayout;